### ISSUE TITLE
Add static compilation or automatically copy dynamic library files when building

### ISSUE THREAD

**Issue by ArcherGu** [k2-fsa/sherpa-ncnn-go-windows#1]
On Windows, I had to copy the `*.dll` files to a sibling directory in the executable to run it. Is it possible to provide statically compiled library files or automatically copy the `*.dll` files to the build output directory.

Thank you so much.

**Comment by csukuangfj** [comment]
Sorry for the late reply.

>  Is it possible to provide statically compiled library files

Yes, I think it is possible. Please create an issue in the sherpa-ncnn repo and we can support it.

----

> automatically copy the *.dll files to the build output directory

I suggest that you just create a `.bat` file containing a command to copy the required DLLs to your current directory
or you can just set the environment variable `PATH` to contain the directory where the DLLs locate.
